services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: JWT_SECRET
        value: my_secret_key
      - key: DATABASE_URL
        fromDatabase:
          name: main-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: main-db
    plan: free
    postgresMajorVersion: 16
